config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "trainings#index"

  resources :trainings,  only: [:new, :create, :show, :edit, :update, :destroy] 
  resources :targets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '休養' },
    { id: 3, name: 'ジョグ' },
    { id: 4, name: 'LSD' },
    { id: 5, name: 'スピード練習' },
    { id: 6, name: 'インターバル練習' },
    { id: 7, name: 'ロング走練習' },
    { id: 8, name: 'ペース走練習' },
    { id: 9, name: 'ビルドアップ走練習' },
    { id: 10, name: '筋力トレーニング' }
  ]

  include ActiveHash::Associations
  has_many :trainings

  end

app/models/target.rb
class Target < ApplicationRecord
  belongs_to :user
 

  with_options presence: true do
    validates :target
    validates :timing
    validates :activity
    validates :reward
  end
end

app/models/training.rb
class Training < ApplicationRecord
 extend ActiveHash::Associations::ActiveRecordExtensions
 belongs_to :category
 belongs_to :user



  with_options presence: true do
    validates :date
    validates :category_id, numericality: { other_than: 1 }
    validates :training_menu, length:{ maximum: 1000}
  end
  validates :comment, length:{ maximum: 1000}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :trainings
  has_one :Target

  with_options presence: true do
    validates :nickname
    validates :email
    validates :encrypted_password, length: { minimum: 6 }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:encrypted_password,:nickname])
  end
# def new
#   @user = User.new
# end

end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  before_action :set_target, only: [:show, :edit, :update, :destroy]

  def index
    @targets = Target.includes(:user)
  end

  def new
    @target = Target.new
  end

  def create
    @target = Target.new(target_params)
    if @target.save
      redirect_to root_path 
    else
      render :new
    end 
  end
  
  def show
  end

  def edit
  end

  def update
    if @target.update(target_params)
      redirect_to root_path 
    else
      render :edit
    end
  end

  def destroy
    training = Target.find(params[:id])
    training.destroy
    redirect_to root_path
  end

  private
  def target_params
    params.require(:target).permit(:target, :timing, :activity, :reward).merge(user_id: current_user.id)
  end


   def set_target

    @target = Target.find(params[:id])
   end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_training, only: [:show, :edit, :update, :destroy]
  before_action :contributor_confirmation, only: [:edit, :update, :destroy]

def index
  @trainings = Training.all.page(params[:page]).per(5).order("created_at DESC")
  @targets = Target.all.order(updated_at: :desc).limit(1)
end

def new
  @training = Training.new
end

def create
  @training = Training.new(training_params)
  if @training.save
    redirect_to root_path 
  else
    render :new
  end 
end

def show
 
end

def edit

end

def update
  if @training.update(training_params)
    redirect_to training_path 
  else
    render :edit
  end
end

def destroy
  training = Training.find(params[:id])
  training.destroy
  redirect_to root_path
end




private
def training_params
  params.require(:training).permit(:date, :training_menu, :category_id, :comment).merge(user_id: current_user.id)
end

def set_training
  @training = Training.find(params[:id])
end

def contributor_confirmation
  redirect_to root_path unless current_user.id == @training.user_id
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>training</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("training6.png", class: :logo), root_path %>
          </div>
            <% if user_signed_in? %> 
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path,  method: :delete, class: :nav__btn, method: :delete %>
              <%= link_to "実施記録", new_training_path, class: :nav__btn %>
              <%= link_to "目標設定", new_target_path, class: :nav__btn %>
             </div> 
            <% else %> 
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
            <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © TRAINING All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/targets/_index.html.erb
<div>

  <% @targets.each do |target|  %>
<table class="target">
      <tbody>
        <tr>
          <th class="arrow_box">目標</th>
          <td ><%= target.target %></td>
        </tr>
        <tr>
          <th class="arrow_box">実施するタイミング</th>
          <td ><%= target.timing %></td>
        </tr>
        <tr>
          <th class="arrow_box">行動内容</th>
          <td ><%= target.activity %></td>
        </tr>
        <tr>
          <th class="arrow_box">報酬</th>
          <td ><%= target.reward %></td> 
        </tr>
      </tbody>
</table>
     <div class=button-area>
        <button class="target-button">
        <%= link_to "目標設定の編集", target_path(target.id), method: :get  %>
      </button>
     </div>
      <% end %>
</div>

app/views/targets/edit.html.erb
<h2 class="page-heading">目標設定</h2>

<%= form_with model: @target, local: true do |f|%>
  

  <div class="field">
    <%= f.label :target, "目標" %><br />
    <%= f.text_area :target, class: :form__text, id:"prototype_concept" %>
  </div>
 
  <div class="field">
    <%= f.label :timing, "実施のタイミング" %><br />
    <%= f.text_area :timing, class: :form__text, id:"prototype_concept" %>
  </div>

  <div class="field">
    <%= f.label :activity, "実施内容" %><br />
    <%= f.text_area :activity, class: :form__text, id:"prototype_concept" %>
  </div>
  <div class="field">
    <%= f.label :reward, "目標達成時の報酬" %><br />
    <%= f.text_area :reward, class: :form__text, id:"prototype_concept" %>
  </div>

  <div class="actions">
    <%= f.submit "設定", class: :form__btn  %>
  </div>
<% end %>

app/views/targets/new.html.erb
<h2 class="page-heading">目標設定</h2>

<%= form_with model: @target, url: targets_path(@target.id), local: true do |f|%>
  

  <div class="field">
    <%= f.label :target, "目標" %><br />
    <%= f.text_area :target, class: :form__text, id:"prototype_concept" %>
  </div>
 
  <div class="field">
    <%= f.label :timing, "実施のタイミング" %><br />
    <%= f.text_area :timing, class: :form__text, id:"prototype_concept" %>
  </div>

  <div class="field">
    <%= f.label :activity, "実施内容" %><br />
    <%= f.text_area :activity, class: :form__text, id:"prototype_concept" %>
  </div>
  <div class="field">
    <%= f.label :reward, "目標達成時の報酬" %><br />
    <%= f.text_area :reward, class: :form__text, id:"prototype_concept" %>
  </div>

  <div class="actions">
    <%= f.submit "設定", class: :form__btn  %>
  </div>
<% end %>

app/views/targets/show.html.erb
<div class="item-explain-box">
      <h2>目標の編集</h2>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">目標</th>
          <td class="detail-value"><%= @target.target %></td>
        </tr>
        <tr>
          <th class="detail-item">実施するタイミング</th>
          <td class="detail-value"><%=@target.timing %></td>
        </tr>
        <tr>
          <th class="detail-item">行動内容</th>
          <td class="detail-value"><%= @target.activity %></td>
        </tr>
        <tr>
          <th class="detail-item">報酬</th>
          <td class="detail-value"><%= @target.reward %></td> 
        </tr>
      </tbody>
    </table>
    <div class="button-whole">
      <button class="button">
        <%= link_to "編集", edit_target_path, method: :get %>
      </button>
      <button class="button">
        <%= link_to "削除", target_path, method: :delete %>
      </button>
      <button class="button">
        <%= link_to "戻る", root_path %>
      </button>
    </div>
  
 

app/views/trainings/_form.html.erb
<%= form_with model: @training, local: true do |f|%>
  

  <div class="field">
    <%= f.label :date, "日付" %><br />
    <%= f.date_field :date, id:"prototype_title" %>
  </div>
 
  <div class="field">
    <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"genre-select"}) %>
  </div>

  <div class="field">
    <%= f.label :training_menu, "トレーニングメニュー" %><br />
    <%= f.text_area :training_menu, class: :form__text, id:"prototype_catch_copy" %>
  </div>

  <div class="field">
    <%= f.label :comment, "トレーニング評価" %><br />
    <%= f.text_area :comment, class: :form__text, id:"prototype_concept" %>
  </div>

  <div class="actions">
    <%= f.submit "設定", class: :form__btn  %>
  </div>
<% end %>

app/views/trainings/_training.html.erb
<%= form_with model: @training, url: training_path, local: true do |f|%>
  

  <div class="field">
    <%= f.label :date, "日付" %><br />
    <%= f.date_field :date, id:"prototype_title" %>
  </div>
 
  <div class="field">
    <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"genre-select"}) %>
  </div>

  <div class="field">
    <%= f.label :training_menu, "トレーニングメニュー" %><br />
    <%= f.text_area :training_menu, class: :form__text, id:"prototype_catch_copy" %>
  </div>

  <div class="field">
    <%= f.label :comment, "トレーニング評価" %><br />
    <%= f.text_area :comment, class: :form__text, id:"prototype_concept" %>
  </div>

  <div class="actions">
    <%= f.submit "設定", class: :form__btn  %>
  </div>
<% end %>

app/views/trainings/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">トレーニング記録の編集</h2>
        <%= render "trainings/training" %>
    </div>
  </div>
</div>

app/views/trainings/index.html.erb
<div class="top__image">
<%= image_tag 'top-image2.png' %>
</div>

<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting">
        <h1>
        こんにちは！
        <%= current_user.nickname %>さん
        </h1>
        <h1>トレーニングを始めよう！！</h1>
      </div> 

<%= render partial: "targets/index" %>



      <div class="title">
        <h2>トレーニング実施記録一覧</h2>
        <table>
        <tr>
    <th>日付</th>
    <th>トレーニングカテゴリー</th>
    <th>詳細</th>
        </tr>
        <% @trainings.each do |training| %>
  <tr>
    <td class="icon">
        <%= training.date %> 
    </td>
    <td>
        <%= training.category.name %> 
    </td>
    <td>
    <button>
    <%= link_to "詳細", training_path(training.id), method: :get %>
    </button>
    </td>
  <tr>
  
    <% end %>
</table>
<%= paginate @trainings %>
     
      </div>
      <% end %>
  </div>
</main>


 

app/views/trainings/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">トレーニング内容の記録</h2>
        <%= render "trainings/form" %>
    </div>
  </div>
</div>

app/views/trainings/show.html.erb
 <div class="item-explain-box">
      
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">日付</th>
          <td class="detail-value"><%= @training.date %></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @training.category.name %></td>
        </tr>
        <tr>
          <th class="detail-item">トレーニングメニュー</th>
          <td class="detail-value"><%= @training.training_menu %></td>
        </tr>
        <tr>
          <th class="detail-item">評価コメント</th>
          <td class="detail-value"><%= @training.comment %></td> 
        </tr>
      </tbody>
    </table>
  </div>
 

    <div class="button-whole">
      <button class="button">
        <%= link_to "編集", edit_training_path, method: :get %>
      </button>
      <button class="button">
        <%= link_to "削除", training_path, method: :delete %>
      </button>
      <button class="button">
        <%= link_to "戻る", root_path %>
      </button>
    </div>
  